### ISSUE TITLE
mysql8.0接入

### ISSUE THREAD

**Issue by 786744873** [didi/Logi-KafkaManager#100]
发现无法使用mysql8.0作为数据库，希望5.x可以升级8.x

**Comment by herry-hu** [comment]
原因：直接打包是不支持mysql8的，Maven中mysql依赖是5.7的，配置文件的驱动也是5.7的。
方法：打包时先把maven中的mysql依赖更新为mysql8，配置文件的驱动更改为：driver-class-name: com.mysql.cj.jdbc.Driver。
pom：
   <dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>8.0.20</version>
            </dependency>
