### ISSUE TITLE
hello，关于application.yml配置文件能否详解下呢

### ISSUE THREAD

**Issue by ccjetweat** [didi/Logi-KafkaManager#107]
custom:
  idc: cn
  jmx:
    max-conn: 10
  store-metrics-task:
    community:
      broker-metrics-enabled: true
      topic-metrics-enabled: true
    didi:
      app-topic-metrics-enabled: true
      topic-request-time-metrics-enabled: true
      topic-throttled-metrics: true
    save-days: 7

account:
  ldap:

kcm:
  enabled: false
  storage:
    base-url: http://127.0.0.1
  n9e:
    base-url: http://127.0.0.1:8004
    user-token: 12345678
    timeout: 300
    account: root
    script-file: kcm_script.sh

monitor:
  enabled: false
  n9e:
    nid: 2
    user-token: 1234567890
    mon:
      base-url: http://127.0.0.1:8032
    sink:
      base-url: http://127.0.0.1:8006
    rdb:
      base-url: http://127.0.0.1:80

notify:
  kafka:
    cluster-id: 95
    topic-name: didi-kafka-notify
  order:
    detail-url: http://127.0.0.1

**Comment by ZQKC** [comment]
今天加一下，立个贴 2020115

**Comment by ccjetweat** [comment]
非常感谢
