### ISSUE TITLE
kafkamanager 在K8S容器中连接MySQL数据库报错

### ISSUE THREAD

**Issue by yangvipguang** [didi/Logi-KafkaManager#115]
1、数据库版本：5.7.11
2、命令行客户端可以连接成功
3、环境：Docker + K8S

现在情况是我把kafkamanager 放到容器中出现报错，但是如果直接java 运行是不报错的，感觉java 版本问题：
![image](https://user-images.githubusercontent.com/11416887/104900104-9db90380-59b6-11eb-8ad3-3cf8ab381a18.png)
![image](https://user-images.githubusercontent.com/11416887/104900811-7d3d7900-59b7-11eb-9066-2b23865eb011.png)

请教下官方滴滴用的什么基础java 镜像有没有遇到这个问题。目前我从openjdk 8-16 都试了一遍。懵逼了。
Dockerfile：
基础镜像：
![image](https://user-images.githubusercontent.com/11416887/104900137-ad384c80-59b6-11eb-9903-6bc7f5c0ec6a.png)
kafkamanager 镜像：
![image](https://user-images.githubusercontent.com/11416887/104900404-00aa9a80-59b7-11eb-8288-bd743a5c0834.png)

**Comment by yangvipguang** [comment]
已解决

**Comment by ZQKC** [comment]
👍  Dockerfile我们之前也实现过一个，但是感觉不是非常友好，方便的话，欢迎贡献相关代码，感谢。不方便的话，也没事 😊

**Comment by yangvipguang** [comment]
@ZQKC   可以的，就是截图的。晚点我整理下可以提供完整Helm和Dockerfile

**Comment by ZQKC** [comment]
感谢🙏
