### ISSUE TITLE
没法查看topic的消息内容吗？

### ISSUE THREAD

**Issue by wajika** [didi/Logi-KafkaManager#116]
没有找到明显的按钮提供这个功能

**Comment by ZQKC** [comment]
在Topic详情页里面，有一个采样的按钮

**Comment by wajika** [comment]
> 在Topic详情页里面，有一个采样的按钮

谢谢 我看到了。 感觉这种类似数据库DML的操作用到的比较多，应该更加"靠近"用户。

**Comment by ZQKC** [comment]
这块有什么建议呢？ @ZHAOYINRUI  寅锐也关注一下

**Comment by iacker** [comment]
- kafka-ui 这个开源项目在 topic 消息内容这块做的不错，可以参考下
  - 链接：https://github.com/provectus/kafka-ui

**Comment by wajika** [comment]
> * kafka-ui 这个开源项目在 topic 消息内容这块做的不错，可以参考下
>   
>   * 链接：https://github.com/provectus/kafka-ui

这个工具我已经用挺久了，感谢分享。

**Comment by ZQKC** [comment]
> * kafka-ui 这个开源项目在 topic 消息内容这块做的不错，可以参考下
>   
>   * 链接：https://github.com/provectus/kafka-ui

感谢建议，我们年后关注一下

**Comment by ZQKC** [comment]
> > * kafka-ui 这个开源项目在 topic 消息内容这块做的不错，可以参考下
> >   
> >   * 链接：https://github.com/provectus/kafka-ui
> 
> 这个工具我已经用挺久了，感谢分享。 如果你们能整和到一起 那就太棒了，你们觉得呢？

嗯嗯，感谢。这个我们关注一下，近期的3.x版本会进行优化，进行优化时，我们也参考一下kafka-ui的设计
