### ISSUE TITLE
请问可以看到一个topic的总消息数么

### ISSUE THREAD

**Issue by Level1Accelerator** [didi/Logi-KafkaManager#117]
topic管理里貌似没看到

**Comment by ZQKC** [comment]
得到Topic详情页面去看：http://117.51.146.109:8080/kafka/topic/topic-detail?clusterId=1&topic=kmo_logi&isPhysicalClusterId=true&region=cn#5

**Comment by ZQKC** [comment]
无更多反馈，关闭问题
