### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by xiaomi-box** [didi/Logi-KafkaManager#121]
首次使用，使用大概10分钟左右，退出登陆，再次登陆，无法登陆，提示用户名密码错误，初始密码未修改

**Comment by ZQKC** [comment]
有什么错误信息么？除了用户名密码错误之外，还有，使用的版本是？

**Comment by xiaomi-box** [comment]
上述问题已处理，运维监控->平台管理->用户管理，编辑用户角色时，密码选项非必选项目，直接确认会存在密码重置为空的情况，建议将密码单独到修改密码，或者在用户不输入密码时默认为原密码

**Comment by ZQKC** [comment]
好的，这个问题我们优化一下。
@ZHAOYINRUI  辛苦也关注一下。

**Comment by ZQKC** [comment]
2.3.0版本中已进行修复
