### ISSUE TITLE
现存topic 申请推送消费权限，审核时报topic not exist

### ISSUE THREAD

**Issue by yhadyh** [didi/Logi-KafkaManager#140]
现存topic 申请推送消费权限，审核时报topic not exist,逻辑集群中是有对应的topic的；
![image](https://user-images.githubusercontent.com/18721182/105845214-603b2280-6015-11eb-8689-4a44fe7579cd.png)

**Comment by ZQKC** [comment]
错误不可避免 ，接下来会对该错误提示进行优化，避免造成困扰
