### ISSUE TITLE
[后端]操作记录检查&补充

### ISSUE THREAD

**Issue by ZQKC** [didi/Logi-KafkaManager#153]
当前对部分操作记录会记录到操作表(operate_record)中，但是存在一些遗漏或者不规范。
期望记录的操作记录有以下几类：
- [ Topic的增删改] 
- [ 集群接入的增删改] 
- [ App的增删改] 
- [权限的删除]

此外，开发的时候，一个类型一个PR。

**Comment by 17hao** [comment]
你好 @ZQKC ，这个issue你开始做了吗？如果没有的话，我可以一起帮忙解决😀

**Comment by ZQKC** [comment]
还没有开始做。多谢帮忙，有问题随时群里沟通 🙏

**Comment by 17hao** [comment]
我按照你列的顺序进行完善，有完成的进度会随时提pr并在这里更新状态🚀

**Comment by ZQKC** [comment]
感谢，老哥方便的话，也入群沟通，github上的消息都是不定时看的，回复的较慢啊

**Comment by 17hao** [comment]
OK，已加钉钉群
