### ISSUE TITLE
执行   mvn clean pcakge 命令kafka-manager-console模块生成的Jar包只有3k

### ISSUE THREAD

**Issue by haiCheng-76** [didi/Logi-KafkaManager#155]
在使用`mvn  clean install`之后，再对kafka-manager-console模块执行`mvn clean package`后target目录下的Jar包只有3K
![](https://www.hualigs.cn/image/6018c9e1458d8.jpg)

是我打包有问题吗？

**Comment by ZQKC** [comment]
没有问题，前端现在打包之后，生存的是静态资源文件，不是jar包。
这个jar包基本无作用，前端资源文件生成的未知在kafka-manager-web/xxx/resources/templates下面

**Comment by haiCheng-76** [comment]
好的 感谢回复

**Comment by ZQKC** [comment]
客气，有问题随时沟通
