### ISSUE TITLE
__consumer_offsets 是否应该出现在topic信息列表页

### ISSUE THREAD

**Issue by 17hao** [didi/Logi-KafkaManager#160]
![image](https://user-images.githubusercontent.com/18420212/106686017-8e67c600-6604-11eb-8ff5-698cb4b3570b.png)
运维管控 -> 集群列表 -> 选择某个集群 -> Topic信息
`__consumer_offsets`会出现在Topic信息列表中。这个topic属于元数据，我认为应该向用户隐藏起来。

**Comment by ZQKC** [comment]
1、这块页面是只有管理员才能看到的页面，我理解管理员应该是可以看到所有的以及对所有的资源进行操作，因此我觉得不应该过滤掉。
2、在Topic管理->全部Topic那块确实不应该出现，避免用户误操作。

@ZHAOYINRUI 产品也看一下这个问题吧

**Comment by ZHAOYINRUI** [comment]
在全部Topic列表也，应该要把这个topic过滤掉。后续，安排优化一下
