### ISSUE TITLE
获取topic分区信息接口延迟过高

### ISSUE THREAD

**Issue by 17hao** [didi/Logi-KafkaManager#161]
![image](https://user-images.githubusercontent.com/18420212/106687945-169b9a80-6608-11eb-9b03-bb92fc5888b9.png)
Topic管理 -> 选择任意topic -> 分区信息
`partitions?dataCenter=cn`接口的延迟高达30s，其他接口均正常。

**Comment by ZQKC** [comment]
耗时高可能原因有：
1、集群的服务地址有问题，导致创建客户端失败，最终导致获取endoffset超时；
2、该Topic存在问题，导致获取endoffset超时；

这块需提供一下Topic信息和集群配置信息，或者查看一下日志，以确定问题点。

正常的接口耗时如下接口：
http://117.51.146.109:8080/kafka/topic/topic-detail?clusterId=4&topic=kmo_logi&region=cn#5

**Comment by 17hao** [comment]
这是我配置的一个集群：http://117.51.146.109:8080/kafka/admin/cluster-detail?clusterId=9#1
查看`test-topic`的[分区信息](http://117.51.146.109:8080/kafka/topic/topic-detail?clusterId=9&topic=test-topic&isPhysicalClusterId=true&region=cn#1)延迟比较高，刚刚试了下其他集群的topic获取分区信息耗时都很正常。
可以帮忙看下我配置的地址有什么问题吗？

**Comment by ZQKC** [comment]
http://117.51.146.109:8080/kafka/admin/cluster-detail?clusterId=9#3 可以看一下这个地址，这个地方展示的主机是aliyun，这个估计会识别不了，从而导致获取endoffset失败。主机这块是否可以配置成IP，方便识别。

**Comment by 17hao** [comment]
### 因为我修改了/etc/hosts文件，所以主机名展示了aliyun
![image](https://user-images.githubusercontent.com/18420212/106708674-3f368b00-662e-11eb-8e62-376842a1072c.png)


### kafka的server.properties中zk地址的配置
![image](https://user-images.githubusercontent.com/18420212/106709843-0ac3ce80-6630-11eb-9a0f-ed354e8cf520.png)


### zk中broker信息
![image](https://user-images.githubusercontent.com/18420212/106709416-73f71200-662f-11eb-9cd6-7d594fa55e97.png)

理论上来说这些配置应该不会影响到获取topic信息🧐，晚上有时间的时候我研究下源码，看看具体是啥原因导致的。
另外JMX的端口也已经开放了。

**Comment by ZQKC** [comment]
可能会影响的，客户端和broker的交互之间是通过ZK上broker元信息中展示的地址的，这个地址错误，会导致通信不了。

**Comment by 17hao** [comment]
@ZQKC 这个实现会不会合理性有待商榷？因为在局域网内配hostname是挺常见的，照目前看好像是直接用这个局域网内使用的hostname作为域名去获取信息了

**Comment by ZQKC** [comment]
配置hostname是没有任何问题的，问题在于这个hostname得能被识别出来，这块感觉应该是网络的问题，而不是在实现上的问题，另外这块在Broker上也是可配置的。

**Comment by ZQKC** [comment]
如果没有更多问题，那么一天后将关闭该ISSUE

**Comment by 17hao** [comment]
抱歉，前几天没看到这个issue的评论。我应该找到问题的原因了
1. jmx连接用的是BrokerMetadata的host字段
https://github.com/didi/Logi-KafkaManager/blob/2672502c079ce542136b3d17c8061f2b10f0a831/kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/cache/PhysicalClusterMetadataManager.java#L300
2. BrokerMetadata的host字段用的是zk节点信息的endpoints中的hostname
https://github.com/didi/Logi-KafkaManager/blob/b74612fa4148ccb5ef6ac89543f5dbf92a708674/kafka-manager-core/src/main/java/com/xiaojukeji/kafka/manager/service/zookeeper/BrokerStateListener.java#L83

但是这个hostname是给局域网的私有ip配的，不能被DNS服务器解析出来，所以获取不到logSize的信息。
这里我觉得用这个hostname去连接是有问题的，一个机房里每台机器的hostname是给私有ip配的，公网解析不了。而且既然已经配置了bootstrap server的地址，可以直接用bootstrap server的地址。

**Comment by 17hao** [comment]
或者可以加一个jmx的响应超时时间`sun.rmi.transport.tcp.responseTimeout=xxx`

**Comment by 17hao** [comment]
不对，我再想了下现在的实现也合理的😂如果kafka manager是私有化部署，和zk、kafka都布在一个机房里，hostname能解析出来，只是我现在用了demo环境网络有问题。
不过扯远点，未来kafka manager如果做成一款SaaS产品，现在的实现就不行了...

**Comment by ZQKC** [comment]
“这里用zk中保存的这个hostname去连接会不会不太合适？一个机房里每台机器的hostname是给私有ip配的，公网解析不了。而且既然已经配置了bootstrap server的地址，可以直接用bootstrap server的地址。”

1、offset信息：bootstrap server只是一个启动时候的服务地址，或者说是引导地址，他会将请求引导到真正的broker去，而真正的broker的地址，也就是zk上的broker的地址。

2、JMX信息：这个信息是需要从每个集群的具体每个broker上进行获取的，现在可以知道的地址就是zk上的broker地址，想要通过bootstrap server获取到全部JMX信息，这个实现不了。

基于以上两点，所以没有使用bootstrap server地址。JMX超时时间那个确实可以加一下。

**Comment by ZQKC** [comment]
如果没有更多问题，那么一天后将关闭该ISSUE

**Comment by 17hao** [comment]
嗯嗯，理解了。先关闭了。
