### ISSUE TITLE
采样功能无法展示原有集群topic中数据，使用平台创建的topic可以

### ISSUE THREAD

**Issue by jihang-web** [didi/Logi-KafkaManager#170]
kafka版本为1.0.0  kafkamanager版本为2.0
![image](https://user-images.githubusercontent.com/55303647/107001158-22cc5700-67c4-11eb-88a9-aed3d4cef801.png)
kafka中有数据，但是采样功能无法展示
日志中报错如下：WARN  o.apache.kafka.clients.consumer.internals.Fetcher - Unknown error fetching data for topic-partition c7674ba7-bbed-447b-88a5-920f2f82a4af-0

**Comment by jihang-web** [comment]
疑似是带中横线的topic无法采样，下划线的可以

**Comment by ZQKC** [comment]
使用2.2.0最新版本测试了一下，没有出现你说的那个问题。这块错误是服务端返回的，这块服务端是否正常，或者是否有什么异常日志，KM除了你发的日志，是否还有其他的日志？

测试的Topic ：http://117.51.146.109:8080/kafka/topic/topic-detail?clusterId=2&topic=kafka-test-github&isPhysicalClusterId=true&region=cn

**Comment by ZQKC** [comment]
无更多反馈，关闭该问题
