### ISSUE TITLE
jmx有用的指标

### ISSUE THREAD

**Issue by Roarain** [didi/Logi-KafkaManager#185]
根据文档，jvm获取的是Fetch、FetchConsumer、Produce，还有哪些有用的指标？

![image](https://user-images.githubusercontent.com/9844376/108995484-245cb100-76d8-11eb-9c68-00045508491f.png)

https://github.com/didi/Logi-KafkaManager/blob/master/docs/user_guide/kafka_metrics_desc.md#3-%E5%AE%9E%E6%97%B6%E8%80%97%E6%97%B6%E6%8C%87%E6%A0%87%E8%AF%B4%E6%98%8E

**Comment by ZQKC** [comment]
这个问题比较大啊，在滴滴内部的场景及配置下，比较有用的还是Fetch、FetchConsumer、Produce这些指标，然后基本上比较有用的指标Logi-KM基本都有了。至于其他的指标，这块得看你想做什么了，如果是做Kafka稳定性的监控，那么还有挺多的，比如副本同步状态、网络线程的Idle、还有一些JVM及机器的指标等等，具体的可以入群沟通交流啊。

**Comment by ZQKC** [comment]
一天后如无更多反馈，则关闭该issue
