### ISSUE TITLE
开发账号接入集群异常

### ISSUE THREAD

**Issue by navyaijm2017** [didi/Logi-KafkaManager#187]
开发账号本身没有接入集群的权限，但是使用了开发账号去接入集群，填写完相关信息提交，直接没有任何报错，建议给用户返回下相关信息，如果没有权限就直接提示没有权限，谢谢

**Comment by ZQKC** [comment]
@ZHAOYINRUI  辛苦关注一下，算是一个BUG，尽快修复一下
