### ISSUE TITLE
host无法解析，日志报错127.0.0.1，详细如下

### ISSUE THREAD

**Issue by MargeDog** [didi/Logi-KafkaManager#207]
2021-03-17 18:42:06.601 [Collect-Metrics-Thread-1-15] ERROR c.x.k.manager.common.utils.jmx.JmxConnectorWrap - JMX connect exception, host:我的ip  port:7070.
java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is:
	java.net.ConnectException: Connection refused (Connection refused)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:131)
	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:235)
报错如上，DNS是可以正常解析出hostname的，且尝试过配置hostname，报错依然出现，UI前端流量监控无法显示
有获取到zookeeper的brokers信息，发现正常的前端流量监控显示的集群host项显示的是hostname，且数据库应该是从zk拉取的数据记录在broker表是和zk记录一致。
        异常的流量监控集群中，zk项的host是IP
        我的疑惑是无论是ip或者是域名，在DNS正常解析的情况下，不应该都可以正常获取到jmx的信息么？为什么域名的情况下可以正常前端显示，而host是IP的情况下无法正常获取，且报错127.0.0.1上述报错

**Comment by ZQKC** [comment]
可以查看一下FAQ，里面有一个JMX链接失败以及如何解决的说明

**Comment by MargeDog** [comment]
@ZQKC 看过那个解决办法，但是好像并不能解决我的问题，报错疑似无法找到hostname，但是部署机器本地的hostname解析是正常的，为什么zk里面存储的是ip，然后根据ip获取jmx信息会无法在UI上显示呢？而zk里面存储的是hostname的情况下，显示就正常了？这个是和代码实现有关？还是和kakfa的jmx获取规则有关呢？

**Comment by ZQKC** [comment]
不好意思，有点不是非常明白，是不是：
1、“为什么zk里面存储的是ip，然后根据ip获取jmx信息会无法在UI上显示呢？”，ZK里面存储的IP是不是kafka配置文件写了ip？这个无法显示是？
2、“而zk里面存储的是hostname的情况下，显示就正常了？”   这个正常是什么正常了？最原始的数据是存储在ZK的，可以对比一下ZK和KM上的数据，看是不是KM解析错了。
3、“还是和kakfa的jmx获取规则有关呢？”，这个是怀疑什么？

**Comment by MargeDog** [comment]
@ZQKC 
不好意思啊，没有表述清楚
1.zk的brokers里面的ids，get出来的节点信息，里面有一项host，当这个host获取到是IP而不是主机名的时候，我发现前端的UI显示实时流量信息不是正常的，都为空值，但是查看页面broker信息栏目的时候jmx的port有正常获取到，对于你说的km解析和zk的信息，我发现是一致的，没有解析错误的情况发生
2.我怀疑的是，当zk的节点信息是ip的时候，流量无法获取，而是主机名的时候却可以，是不是无法根据ip获取到dns解析出来的hostname导致的呢，还是说和kafka里面配置项里的host.name有关？

**Comment by ZQKC** [comment]
1、JMX-PORT这个数据也是从ZK里面的Broker信息里面解析出来的，这个正常仅仅表示配置了，但是是否正确不好确定。
2、第二点这个，具体还是得看一下JMX的实现，对这块的实现不是非常了解。我觉得应该还是Kafka哪里的配置有问题导致的。

**Comment by ZQKC** [comment]
是否还有问题，如果无更多问题，一天后将关闭该issue
