### ISSUE TITLE
前端想使用Nginx代理 该如何配置？

### ISSUE THREAD

**Issue by Interesting993** [didi/Logi-KafkaManager#213]
想使用Nginx做个代理 该如何配置？ 当下情况是，前端Nginx代理后，看Nginx日志存在404。

**Comment by ZQKC** [comment]
入群咨询一下吧，这块有个用户已经配置成功了，后续我们搞个demo在上面

**Comment by Interesting993** [comment]
解决了。在条件允许的情况下，可以将nginx的一个端口完全代理给Kafka-manager服务。供参考：
    server {
        listen      8000;
        server_name  127.0.0.1;
        access_log  /etc/nginx/logs/kafka-manager.log  main;

    location / {
      #proxy_redirect off;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass http://kafka-manager服务器IP:8080;
    }
    }

目前验证，暂时没有发现问题
