### ISSUE TITLE
是否可以支持mysql 8.x版本

### ISSUE THREAD

**Issue by hagang** [didi/Logi-KafkaManager#220]
如题，现在只支持mysql 5.x版本

**Comment by shirenchuang** [comment]
> 如题，现在只支持mysql 5.x版本

可以自己先改一下pom引用8.0+就行了  再把Driver改一下

`
            <dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>8.0.11</version>
            </dependency>
`
application.yml 
`
      driver-class-name: com.mysql.cj.jdbc.Driver
`

**Comment by hagang** [comment]
好的，多谢啦
