### ISSUE TITLE
建议可以增加一个开关，来决定是否开启工单的【自动审批】功能

### ISSUE THREAD

**Issue by kxbin** [didi/Logi-KafkaManager#226]
目前，申请逻辑集群、申请Topic，这一类工单，每分钟会默认进行自动审批，建议增加开关控制

**Comment by cobolbaby** [comment]
申请应用会自动审批通过，但是申请逻辑集群、申请Topic会自动审批？

**Comment by ZQKC** [comment]
申请集群不会，申请Topic可以做到自动化审批
