### ISSUE TITLE
独享集群和独立集群有什么区别？

### ISSUE THREAD

**Issue by cobolbaby** [didi/Logi-KafkaManager#236]

**Comment by shirenchuang** [comment]
可以看看这篇文章
https://blog.csdn.net/u010634066/article/details/115402309

**Comment by cobolbaby** [comment]
@shirenchuang 您推荐的文章中这两个概念和当前项目的[使用手册](https://github.com/didi/Logi-KafkaManager/blob/master/docs/user_guide/user_guide_cn.md)中提到的有出入，建议修正一下。

**Comment by shirenchuang** [comment]
> @shirenchuang 您推荐的文章中这两个概念和当前项目的[使用手册](https://github.com/didi/Logi-KafkaManager/blob/master/docs/user_guide/user_guide_cn.md)中提到的有出入，建议修正一下。

使用手册的把独立和独享的概念写反了 ；我去提个pr

**Comment by shirenchuang** [comment]
> @shirenchuang 您推荐的文章中这两个概念和当前项目的[使用手册](https://github.com/didi/Logi-KafkaManager/blob/master/docs/user_guide/user_guide_cn.md)中提到的有出入，建议修正一下。

@cobolbaby  使用手册的把独立和独享的概念写反了 ；我去提个pr
