### ISSUE TITLE
Docker 运行无法连接数据库

### ISSUE THREAD

**Issue by yangvipguang** [didi/Logi-KafkaManager#237]
直接虚拟机java 启动没有问题。但是我用容器启动（java 8  java 12  java 16 都试了）。连接是用的公网IP 和 svc name 都试了。都会报错如下：
![image](https://user-images.githubusercontent.com/11416887/115667280-3bd2b600-a378-11eb-9596-a6750ea074ec.png)
![image](https://user-images.githubusercontent.com/11416887/115667312-455c1e00-a378-11eb-920d-c778be813c2d.png)

我之前成功过。不知道现在啥原因。有人遇到过么

**Comment by ZQKC** [comment]
底层驱动包有做个一次升级，升级成支持8.x版本的mysql了，这块是否可能会有影响？

**Comment by yangvipguang** [comment]
@ZQKC   是哪个版本升级的。

**Comment by ZQKC** [comment]
2.3.0之后的版本

**Comment by yangvipguang** [comment]
@ZQKC   已经解决了，估计是K8S 集群网络问题，换成集群外数据库就好了，具体问题得抓包看下，和代码应该没关系。

**Comment by ZQKC** [comment]
嗯，好的
