### ISSUE TITLE
开发者角色为什么能够访问运维管控

### ISSUE THREAD

**Issue by cobolbaby** [didi/Logi-KafkaManager#241]
关于开发者和普通用户这两个角色的定义有点困惑，为什么允许开发者访问运维管控，运维管控下面的东西不是运维角色应该操心的吗？

**Comment by ZQKC** [comment]
普通用户：使用Kafka的用户，主要是编写生产者消费者的用户；
开发者：对Kafka进行功能开发等的用户，即负责Kafka的团队，有点类似该平台的运营人员类似；
让开发者可以看到运维管控是因为开发者有时候需要依据运维管控侧的信息定位问题等，但是仅仅只能查看，不能操作。

**Comment by cobolbaby** [comment]
懂了。

那如果这么说的话，开发者又与运维有啥区分呢？平台的开发者应该与Kafka的运维人员是一拨人吧。难道针对一个基础服务，还要分出开发和运维两拨人吗？还是说只是为了切分只读权限和可读可操纵权限而衍生的一个概念?

**Comment by ZQKC** [comment]
是两波人。开发不仅是Logi-KM平台的开发，还有针对Kafka-Broker的开发。
