### ISSUE TITLE
对接夜莺时，告警组该如何创建？

### ISSUE THREAD

**Issue by ZQKC** [didi/Logi-KafkaManager#260]

**Comment by lxy135265** [comment]
![image](https://user-images.githubusercontent.com/38179142/116228020-585f5b80-a787-11eb-971c-b8169c81e184.png)
新建告警规则时可以看到报警接收组的选择框，第一次接触logi-KM会发现这个值是空的。这个值的获取方式是需要前往夜莺平台-用户资源中心-团队管理中新建团队。新建过团队之后再次回到logi-KM中刷新页面就可以看到该文本框可以选到接收组了。

**Comment by ZQKC** [comment]
方便的话，辛苦提个PR，直接在FAQ里面进行说明，issue仅记录问题

**Comment by ZQKC** [comment]
已优化到FAQ中，关闭该issue
