### ISSUE TITLE
期望tomat依赖包升级

### ISSUE THREAD

**Issue by trockxi** [didi/Logi-KafkaManager#298]
https://s.tencent.com/research/bsafe/1018.html
基于安全考虑，需要依赖包也进行升级
![image](https://user-images.githubusercontent.com/28647418/118793081-d7e5d380-b8ca-11eb-8500-bedc70f69ed5.png)

**Comment by trockxi** [comment]
抱歉，依赖包需要再升级
https://s.tencent.com/research/bsafe/1049.html
个人建议直接升级到最新的8.5.66

**Comment by ZQKC** [comment]
嗯嗯，感谢提醒，我再修改一下
