### ISSUE TITLE
集群申请功能无用，存在的意义是什么？

### ISSUE THREAD

**Issue by riyuetianmu** [didi/Logi-KafkaManager#302]
创建逻辑集群后，所有用户均有逻辑集群的权限，集群申请前后无任何变化，请问这里的集群申请存在的意义是什么？

**Comment by ZQKC** [comment]
两个问题：
1、所有用户均有集群权限：这个并不是的，可以设置一个独享集群看一下。
2、申请集群前后无变化：整个流程上暂未彻底的打通，现在的版本是给普通的用户一个申请集群的表达入口。但是还未给运维用户在审批的时候，一个平台化的功能，后续这块要进行打通。

**Comment by riyuetianmu** [comment]
感谢解答，请问集群申请和运维打通功能有计划没有

**Comment by ZQKC** [comment]
> 感谢解答，请问集群申请和运维打通功能有计划没有

短期还无计划。

1、现在搭建一套新的集群，已经和夜莺打通了，但是使用成本上还比较高，现在是计划将这块的使用成本降低下来之后，再考虑打通，不然感觉即使打通了，最后一步搭建比较难使用，收益也不明显。

2、另外一点，现在对于扩缩Broker之后的Topic的均衡等能力，感觉是使用Kafka上更大的痛点，所以近期考虑先增加该功能特性。

老哥要是对集群打通这块有兴趣，欢迎入群沟通交流，也欢迎贡献PR。

**Comment by riyuetianmu** [comment]
谢谢及时回复，我这边先加群沟通下
