### ISSUE TITLE
普通用户申请topic权限后，管理员看不到审批的工单

### ISSUE THREAD

**Issue by riyuetianmu** [didi/Logi-KafkaManager#304]
普通用户申请topic权限后，管理员看不到审批的工单

**Comment by ZQKC** [comment]
> 普通用户申请topic权限后，管理员看不到审批的工单

Topic权限是由Topic所属的应用的负责人进行审批的，并非是管理员审批

**Comment by riyuetianmu** [comment]
你好，应用负责人也查询不到审批单

**Comment by riyuetianmu** [comment]
在全部列表中可以查询，在审批中列表中不能查询
![image](https://user-images.githubusercontent.com/48109460/119428954-71d0d480-bd40-11eb-8bac-883777210d46.png)
![image](https://user-images.githubusercontent.com/48109460/119428970-79907900-bd40-11eb-8b48-a9c54826f881.png)

**Comment by riyuetianmu** [comment]
找到原因了，我申请的topic是从后台通过命令创建的topic，目前看来只能申请从平台创建的topic

**Comment by ZQKC** [comment]
> 找到原因了，我申请的topic是从后台通过命令创建的topic，目前看来只能申请从平台创建的topic

好的。然后还可以看一下FAQ，后台创建的是可以同步到DB的。

**Comment by riyuetianmu** [comment]
好的，谢谢
