### ISSUE TITLE
代码中对zookeeper的操作都是基于根目录，不支持一个zookeeper配置多套kafka集群的场景

### ISSUE THREAD

**Issue by riyuetianmu** [didi/Logi-KafkaManager#307]
代码中对zookeeper的操作都是基于根目录，不支持一个zookeeper配置多套kafka集群的场景（类似172.10.0.1/kafka1， 172.10.0.1/kafka2这种一个zk集群配置多套kafka集群场景）

**Comment by ZQKC** [comment]
支持的。接入集群的时候，就是带节点的。比如接入时是172.10.0.1/kafka1，那么后续都只对172.10.0.1/kafka1目录下的数据做操作
