### ISSUE TITLE
JMX认证问题

### ISSUE THREAD

**Issue by riyuetianmu** [didi/Logi-KafkaManager#313]
配置JMX认证，连接失败
原因已经找到，用户名和密码类型传递错误，看源码应该是string数组，这里传递的时List
JmxConnectorWrap类
 if (!ValidateUtils.isBlank(this.jmxConfig.getUsername()) && !ValidateUtils.isBlank(this.jmxConfig.getPassword())) {
                environment.put(JMXConnector.CREDENTIALS,  Arrays.asList(this.jmxConfig.getUsername(), this.jmxConfig.getPassword()));
            }

修改为：
 if (!ValidateUtils.isBlank(this.jmxConfig.getUsername()) && !ValidateUtils.isBlank(this.jmxConfig.getPassword())) {
                environment.put(JMXConnector.CREDENTIALS, new String[]{this.jmxConfig.getUsername(), this.jmxConfig.getPassword()});
            }
![image](https://user-images.githubusercontent.com/48109460/119928073-6cc48d00-bfad-11eb-913e-82389502ea0d.png)

**Comment by ZQKC** [comment]
👍，老哥方便的话，辛苦来个PR吧
