### ISSUE TITLE
对接夜莺监控系统

### ISSUE THREAD

**Issue by zhushanwei** [didi/Logi-KafkaManager#314]
monitor:
  enabled: true
  n9e:
    nid: 2
    user-token: 123456
    # 夜莺 mon监控服务 地址
    mon:
      base-url: http://127.0.0.1:8000
    # 夜莺 transfer上传服务 地址
    sink:
      base-url: http://127.0.0.1:8000
    # 夜莺 rdb资源服务 地址
    rdb:
      base-url: http://127.0.0.1:8000
搭建过程时发现， 对接v4 版本的夜莺，端口都是8000端口

**Comment by ZQKC** [comment]
> monitor:
> enabled: true
> n9e:
> nid: 2
> user-token: 123456
> # 夜莺 mon监控服务 地址
> mon:
> base-url: http://127.0.0.1:8000
> # 夜莺 transfer上传服务 地址
> sink:
> base-url: http://127.0.0.1:8000
> # 夜莺 rdb资源服务 地址
> rdb:
> base-url: http://127.0.0.1:8000
> 搭建过程时发现， 对接v4 版本的夜莺，端口都是8000端口

嗯嗯，是的。老哥有兴趣的话，欢迎贡献PR，对这块进行修改

**Comment by ZQKC** [comment]
先提前修复了
