### ISSUE TITLE
我的集群，申请集群后没反应

### ISSUE THREAD

**Issue by relsol** [didi/Logi-KafkaManager#318]
申请集群后，通过审批，回到列表页面没有数据
![image](https://user-images.githubusercontent.com/19529001/120176641-1b7cfd80-c23a-11eb-9e9f-50fe000ed738.png)
![image](https://user-images.githubusercontent.com/19529001/120176709-318abe00-c23a-11eb-8407-684c28c1138c.png)

**Comment by ZQKC** [comment]
可以看一下Readme里面的FAQ

**Comment by ZQKC** [comment]
无更多反馈，关闭该issue
