### ISSUE TITLE
单副本5节点的kafka集群宕机一台broker产生的疑问

### ISSUE THREAD

**Issue by devin-df** [didi/Logi-KafkaManager#331]
我这边有几个经历：
单副本5节点的kafka集群宕机一台broker，生产者客户端会即时报出异常，宕机的broker连接异常；异常持续一段时间后，生产者客户端已没有异常消息，消息生产正常。kafka会不会有这样的机制，客户端可以拿到元信息，不再往异常broker所拥有的分区发送消息，把消息都生产到了还正常的分区内

**Comment by ZQKC** [comment]
> 我这边有几个经历：
> 单副本5节点的kafka集群宕机一台broker，生产者客户端会即时报出异常，宕机的broker连接异常；异常持续一段时间后，生产者客户端已没有异常消息，消息生产正常。kafka会不会有这样的机制，客户端可以拿到元信息，不再往异常broker所拥有的分区发送消息，把消息都生产到了还正常的分区内

可以看一下生产消息的时候，分区选择那一块的代码 (org.apache.kafka.clients.producer.KafkaProducer类里面的partition方法)，对于没有设置key的消息，会选择available的分区，不会选择到不可用的分区。更多信息可以看一下代码，包括消费者的。

**Comment by ZQKC** [comment]
无更多反馈，关闭该issue
