### ISSUE TITLE
期望jackson-databind依赖包升级

### ISSUE THREAD

**Issue by trockxi** [didi/Logi-KafkaManager#334]
https://s.tencent.com/research/bsafe/1205.html
基于安全考虑，需要依赖包也进行升级，辛苦大佬升级
https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind

**Comment by ZQKC** [comment]
> https://s.tencent.com/research/bsafe/1205.html
> 基于安全考虑，需要依赖包也进行升级，辛苦大佬升级
> https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind

感谢提出，这两天我们看一下，好升级的话我们这周就升级掉。
