### ISSUE TITLE
针对多地域多机房多集群的场景，Logi-KM管理服务的部署策略

### ISSUE THREAD

**Issue by cobolbaby** [didi/Logi-KafkaManager#348]
针对多地域多机房的场景，Kafka集群往往有很多套，此时Logi-KM的部署策略是什么？是用一套服务进行集中式管理还是分散部署分散管理？滴滴是怎么做的，有没有类似的部署结构图？

**Comment by ZQKC** [comment]
> 针对多地域多机房的场景，Kafka集群往往有很多套，此时Logi-KM的部署策略是什么？是用一套服务进行集中式管理还是分散部署分散管理？滴滴是怎么做的，有没有类似的部署结构图？

KM和多地域多机房之间的网络如何？如果网络没有问题，可以只部署一套KM。如果是机房之间网络延迟高，则建议是一个机房或者一个地域部署一套，但是不建议部署的非常多。

**Comment by cobolbaby** [comment]
感谢．
