### ISSUE TITLE
怎么配置 “SASL JAAS配置“

### ISSUE THREAD

**Issue by lougxing** [didi/Logi-KafkaManager#44]
我的kafka配置

::::::::::::::
kafka_server.properties:
::::::::::::::
listeners=SASL_PLAINTEXT://:19092
security.inter.broker.protocol=SASL_PLAINTEXT
sasl.mechanism.inter.broker.protocol=SCRAM-SHA-256
sasl.enabled.mechanisms=SCRAM-SHA-256
allow.everyone.if.no.acl.found=false
super.users=User:admin
authorizer.class.name=kafka.security.auth.SimpleAclAuthorizer

::::::::::::::
kafka_client_jaas.conf
::::::::::::::
KafkaClient {
    org.apache.kafka.common.security.scram.ScramLoginModule required
    username="admin"
    password="12345678";
};

::::::::::::::
kafka_server_jaas.conf
::::::::::::::
KafkaServer {
    org.apache.kafka.common.security.scram.ScramLoginModule required
    username="admin"
    password="12345678";
};

页面无法显示消费组信息。

**Comment by lougxing** [comment]
java.lang.NullPointerException: null
	at com.xiaojukeji.kafka.manager.service.service.impl.TopicServiceImpl.getTopicPartitionOffset(TopicServiceImpl.java:192)
	at com.xiaojukeji.kafka.manager.service.service.impl.TopicServiceImpl.getTopicPartitionDTO(TopicServiceImpl.java:146)

**Comment by ZQKC** [comment]
因为没有配置上SASL，所以导致客户端创建失败，最终导致这几个接口获取数据失败，SASL的配置可以试一下：

安全协议：SASL_PLAINTEXT
SASL机制：SCRAM-SHA-256
SASL JAAS配置：org.apache.kafka.common.security.scram.ScramLoginModule required  username="admin" password="12345678";

JAAS的这个配置的username和password需要看一下你们的客户端是怎么配置的，大体是这样的。

**Comment by lougxing** [comment]
我是这么配置，不显示消费组信息。

**Comment by ZQKC** [comment]
JDK版本是？？要求是JDK 8进行打包，JDK 11不行，具体或可以入群私聊

**Comment by huangpeng0817** [comment]
> 因为没有配置上SASL，所以导致客户端创建失败，最终导致这几个接口获取数据失败，SASL的配置可以试一下：
> 
> 安全协议：SASL_PLAINTEXT
> SASL机制：SCRAM-SHA-256
> SASL JAAS配置：org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="12345678";
> 
> JAAS的这个配置的username和password需要看一下你们的客户端是怎么配置的，大体是这样的。

最新版本有个安全协议填写，里面内容怎么写？我们集群也是有sasl，测试按照这样格式写，连不上集群。。

**Comment by junfei** [comment]
你用2.1.0版本，会有个提示。
{ 
  "security.protocol": "SASL_PLAINTEXT", 
  "sasl.mechanism": "PLAIN", 
  "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"xxxx\" password=\"xxxxx\";"
}

**Comment by junfei** [comment]
你用2.1.0版本，会有个提示。
{
"security.protocol": "SASL_PLAINTEXT",
"sasl.mechanism": "PLAIN",
"sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"xxxx\" password=\"xxxxx\";"
}

记得账号密码那里的双引号加个转义字符，不然两个双引号会报错

**Comment by ZQKC** [comment]
在接入集群的地方，已有配置SASL的例子，因此关闭该ISSUE
