### ISSUE TITLE
展示topic消费速度

### ISSUE THREAD

**Issue by Jiker4836** [didi/Logi-KafkaManager#52]
1、审批时需要选择分区：看看是否可以向kafka manage只需要写分区数量自动设置分区，或者有提供更加友好的选择分区数
2、topic列表展示流入qps和流量入流量，是否可以加上流出流量，导出数据，方便优化时是做消费和生产流量对比

**Comment by ZQKC** [comment]
1、不是特别明白第一点的需求是什么，方便的话可以入群沟通一下。
2、功能都是可以添加的，只是好奇具体的使用场景是什么？我们原本也是会展示流出流量的，但是后来发现不怎么使用，于是修改成了QPS。
