### ISSUE TITLE
用户管理这块有计划支持接入ldap吗

### ISSUE THREAD

**Issue by zhaoge77** [didi/Logi-KafkaManager#53]
如题。

**Comment by ZQKC** [comment]
2.0版本，用户管理这块具备SSO的方式接入，但是LDAP这个不知道你们是以怎么样的方式接入。具体的可以入群私聊，到时候我们看2.0版本的是否已经支持了，如果不支持，看如何调整。

**Comment by zhaoge77** [comment]
谢谢回答。类似于Grafana的ldap配置，不同的ldap用户组可以映射到kafka-manager里的3个组：管理员、运维人员、普通人员。这样就是经过简单配置可以在企业内部用同一套用户名密码登陆所有内部系统。简化用户的管理

**Comment by ZQKC** [comment]
我们这边应该也是支持的，我们也会和夜莺的一些功能进行对接。但是有一点不同的是，用户角色(管理员、运维人员、普通人员)这块还是在kafka-manager里面配置的，这块应该是不会进行对接。
