### ISSUE TITLE
应用下线后依然存在于展示页面

### ISSUE THREAD

**Issue by cell13** [didi/Logi-KafkaManager#85]
问题：应用下线后，下线调的应用依然存在与展示页面
操作：
1、运维管控-》平台管理-》应用管理-》申请下线默认存在的应用 km-admin-tmp（连接信息，无连接），提示下线成功
2、刷新应用管理展示页面，已经下线的应用 km-admin-tmp 依然存在
3、再次尝试申请下线 应用 km-admin-tmp，报错 app not exit

**Comment by ZQKC** [comment]
1、可以查看一下app表是否还存在km-admin-tmp这个应用
2、如果还存在，可以新申请一个，看一下是否有一样的问题，因为 km-admin-tmp 这个应用初始化的SQL有点问题，现在已经进行了修复。我这边测试已暂无问题。
