### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by yuxueliangluoyang** [didi/Logi-KafkaManager#96]
项目按照指引启动成功，在登录页使用admin账号，点击登录无跳转，前端报错
login:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input

**Comment by yuxueliangluoyang** [comment]
上边的问题是我按照指导在iterm中启动的。我在idea中打开后，重新打包编译，修改数据库用户名密码为本地的库后，可以正常登录了

**Comment by yuxueliangluoyang** [comment]
> 项目按照指引启动成功，在登录页使用admin账号，点击登录无跳转，前端报错
> login:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input

上边的问题是我按照指导在iterm中启动的。我在idea中打开后，重新打包编译，修改数据库用户名密码为本地的库后，可以正常登录了

**Comment by ZQKC** [comment]
有后端相关的启动日志么？“修改数据库用户名密码为本地的库后”这个操作具体是指？

**Comment by yuxueliangluoyang** [comment]
> 有后端相关的启动日志么？“修改数据库用户名密码为本地的库后”这个操作具体是指？

就是web模块下的application.yml文件，里边配置的本地数据库连接信息跟我本地已有的数据库连接用户密码信息不一样，改成自己的用户名密码就好了，
![image](https://user-images.githubusercontent.com/39185382/100955222-1708ae00-3551-11eb-97a4-c2e510d86664.png)

**Comment by ZQKC** [comment]
嗯，好的，那我这个issue就关了
