### ISSUE TITLE
无法对接夜莺告警系统

### ISSUE THREAD

**Issue by junrongfu** [didi/Logi-KafkaManager#97]
目前的kakfa-manager这个jar包,无法对接夜莺告警系统,配置的时候报错：
Caused by :org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'abstractMonitor': Injection of autowired dependencies failed.

**Comment by ZQKC** [comment]
请问这个是那个版本的代码，辛苦提供一下。或者是直接使用最新版本的安装包

**Comment by ZQKC** [comment]
无更多反馈，关闭issue，更多信息可参考FAQ文档
