### ISSUE TITLE
如何接入其他的监控报警？

### ISSUE THREAD

**Issue by FredCof** [didi/Logi-KafkaManager#99]

**Comment by lizhuangs** [comment]
同问，不能直接内置支持邮件、钉钉报警？还要二次开发？

**Comment by ZQKC** [comment]
监控告警默认对接夜莺，依赖夜莺的能力进行邮件及钉钉的报警。如果要对接自己的系统，需要进行一定的二次开发，这块2021-01-17给个文档吧。
